'use client';
import {useMemo,useState,useRef} from 'react';
import {BookOpen,Upload,Search,ChevronLeft,ChevronRight,Check,Eye,EyeOff,Bookmark,Printer,Highlighter,FileText,ArrowRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {toast} from 'sonner';
import {Study,Note} from '@/lib/study';
import {subjects} from '@/lib/content';
import {splitNote} from '@/lib/note-review';
type Props={data:Study;update:(fn:(d:Study)=>Study)=>void;noteId:string;add:()=>void};
export function NotesReview({data,update,noteId,add}:Props){
 const [query,setQuery]=useState(''),[subject,setSubject]=useState('all');const note=data.notes.find(n=>n.id===noteId);
 if(note)return <Reader key={note.id} note={note} data={data} update={update}/>;
 const list=data.notes.filter(n=>(subject==='all'||n.subject===+subject)&&[n.title,n.text,n.tags,n.unit,n.topic].join(' ').toLowerCase().includes(query.toLowerCase()));
 const last=data.notes.find(n=>n.id===data.lastNote);
 return <><div className="page-heading"><div><div className="eyebrow">YOUR MATERIALS. YOUR PACE.</div><h1>Review my notes</h1><p>Paste your lecture notes or upload a file. Read everything here, one section at a time.</p></div><button className="btn primary" onClick={add}><Upload size={18}/>Paste or upload notes</button></div>
 <div className="review-intro card"><BookOpen size={30}/><div><h2>Turn your notes into a study session.</h2><p>1. Add notes &nbsp; 2. Read each section &nbsp; 3. Hide it and explain it in your own words</p><small>Your full text stays available. Sections organize the text; they do not summarize or verify it.</small></div></div>
 {last&&<a className="review-resume" href={'#review/'+last.id}><div><small>CONTINUE YOUR PERSONAL REVIEW</small><strong>{last.title}</strong></div><ArrowRight size={20}/></a>}
 <div className="review-filters"><label className="review-search"><Search size={18}/><input aria-label="Search personal notes" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your notes, topics, or tags…"/></label><select aria-label="Filter personal notes by subject" value={subject} onChange={e=>setSubject(e.target.value)}><option value="all">All subjects</option>{subjects.map((s,i)=><option key={s} value={i}>{s}</option>)}</select></div>
 <p className="small">{list.length} personal {list.length===1?'note':'notes'} available</p>
 {list.length?<div className="notes-grid">{list.map(n=>{const sections=splitNote(n.text);const done=sections.filter(s=>data.noteReview?.[n.id]?.completed?.includes(s.key)).length;return <a className="card personal-note" href={'#review/'+n.id} key={n.id}><span className="pill">Student notes</span><h3>{n.title}</h3><p>{subjects[n.subject]}</p><small>{n.unit}{n.topic?' / '+n.topic:''}</small><p className="note-preview">{n.text.slice(0,180)||'Original saved. Add a transcription to start reviewing.'}</p><Progress value={sections.length?done/sections.length*100:0}/><p className="small">{done} / {sections.length} sections reviewed</p><span className="text-button">Start reviewing <ArrowRight size={16}/></span></a>})}</div>:<section className="card empty"><FileText size={32}/><h2>{data.notes.length?'No matching notes':'Your reviewer starts with your notes'}</h2><p>{data.notes.length?'Try a different search or subject.':'Paste detailed lecture notes, or upload PDF, DOCX, TXT, or an image. Existing notes will also appear here.'}</p><button className="btn primary" onClick={add}>Add notes to review</button></section>}
 </>;
}
function Reader({note:n,data,update}: {note:Note;data:Study;update:Props['update']}){
 const sections=useMemo(()=>splitNote(n.text),[n.text]);const record=data.noteReview?.[n.id];
 const [active,setActive]=useState(()=>Math.max(0,sections.findIndex(s=>s.key===record?.last))),[mode,setMode]=useState('focus'),[hidden,setHidden]=useState(false),[find,setFind]=useState(''),[large,setLarge]=useState(false);
 const content=useRef<HTMLDivElement>(null);const section=sections[active];const completed=record?.completed||[];const count=sections.filter(s=>completed.includes(s.key)).length;
 function patch(value:Partial<NonNullable<Study['noteReview']>[string]>){update(d=>({...d,lastNote:n.id,noteReview:{...d.noteReview,[n.id]:{completed:[],recall:{},...d.noteReview?.[n.id],...value}}}));}
 function jump(i:number){setActive(i);setHidden(false);patch({last:sections[i].key});document.getElementById('review-reading')?.scrollIntoView({behavior:'smooth',block:'start'});}
 function highlight(){const selection=window.getSelection();if(!selection||!content.current?.contains(selection.anchorNode)||!content.current?.contains(selection.focusNode)||!selection.toString().trim()){toast.info('Select text inside your notes first.');return;}const text=selection.toString().trim();update(d=>({...d,highlights:{...d.highlights,[n.id]:[...new Set([...(d.highlights[n.id]||[]),text])]}}));toast.success('Passage saved to highlights.');}
 function marked(text:string){if(!find.trim())return text;const q=find.toLowerCase(),lower=text.toLowerCase();const out:React.ReactNode[]=[];let start=0,index=lower.indexOf(q);while(index>=0){out.push(text.slice(start,index),<mark key={index}>{text.slice(index,index+q.length)}</mark>);start=index+q.length;index=lower.indexOf(q,start);}out.push(text.slice(start));return out;}
 return <><a className="text-button back" href="#review"><ChevronLeft size={16}/>All my review notes</a><div className="page-heading"><div><div className="eyebrow">STUDENT-SUPPLIED · NOT CLINICALLY VERIFIED</div><h1>{n.title}</h1><p>{subjects[n.subject]} / {n.unit}{n.topic?' / '+n.topic:''}</p></div><div className="button-row"><a className="btn secondary" href={'#notes/'+n.id}>Edit & organize</a><button className="btn secondary" onClick={()=>window.print()}><Printer size={17}/>Print review</button></div></div>
 <div className="review-progress"><span>{count} of {sections.length} sections reviewed</span><Progress value={sections.length?count/sections.length*100:0}/><small>Marked by you, not a test of mastery</small></div>
 <details className="review-notices"><summary>Original file & extraction notices ({n.flags.length})</summary>{n.fileId&&<a className="btn secondary" href={'/api/files?id='+n.fileId}>Open original file</a>}<ul>{n.flags.map((f,i)=><li key={i}>{f}</li>)}</ul><p>Reading sections keep the full working text in order. Tables and images may need the original file. No AI explanation or medical verification is applied.</p></details>
 {!sections.length?<section className="card empty"><h2>This note needs readable text</h2><p>The original is preserved. Images and scanned PDFs need a manual transcription before they can appear in the reader.</p><a className="btn primary" href={'#notes/'+n.id}>Add transcription</a></section>:<div className="personal-review-layout"><aside className="card review-outline"><h3>In this note</h3><label className="review-search"><Search size={16}/><input aria-label="Find in this note" placeholder="Find a word or phrase…" value={find} onChange={e=>{setFind(e.target.value);if(e.target.value)setMode('full');}}/></label><nav aria-label="Note sections">{sections.map((s,i)=><button key={s.key} className={i===active?'active':''} onClick={()=>{setMode('focus');jump(i)}}><span>{completed.includes(s.key)?<Check size={16}/>:String(i+1).padStart(2,'0')}</span><span>{s.title}</span></button>)}</nav><button className="btn secondary full" onClick={()=>update(d=>({...d,bookmarks:d.bookmarks.includes(n.id)?d.bookmarks.filter(x=>x!==n.id):[...d.bookmarks,n.id]}))}><Bookmark size={16}/>{data.bookmarks.includes(n.id)?'Bookmarked':'Bookmark note'}</button></aside>
 <section className={'card personal-reader '+(large?'large-reading':'')} id="review-reading"><div className="print-only review-print"><h2>{mode==='summary'?'My quick review summary':'Full detailed notes'}</h2><div className="review-note-text">{mode==='summary'?n.summary:n.text}</div></div><Tabs value={mode} onValueChange={v=>{setMode(v);setHidden(false)}}><TabsList><TabsTrigger value="focus">Section review</TabsTrigger><TabsTrigger value="full">Full detailed notes</TabsTrigger><TabsTrigger value="summary">My summary</TabsTrigger></TabsList>
 <div className="reading-tools"><button className="text-button" onClick={()=>setLarge(!large)}>{large?'Standard text':'Larger text'}</button><button className="text-button" onClick={highlight}><Highlighter size={16}/>Save selected text</button></div>
 <div ref={content}><TabsContent value="focus"><div className="section-title"><small>SECTION {active+1} OF {sections.length}</small><button className="btn secondary" onClick={()=>setHidden(!hidden)}>{hidden?<Eye size={16}/>:<EyeOff size={16}/>} {hidden?'Reveal notes':'Hide & recall'}</button></div><h2>{section.title}</h2>{hidden?<div className="recall-cover"><BookOpen size={28}/><h3>What do you remember?</h3><p>Explain the key ideas, why they matter, and what you would do in a clinical situation. Reveal the notes to check what you missed.</p></div>:<div className="review-note-text">{marked(section.text)}</div>}
 <div className="recall-writing"><label htmlFor="recall">Explain this section in your own words</label><textarea id="recall" rows={5} value={record?.recall?.[section.key]||''} onChange={e=>patch({recall:{...record?.recall,[section.key]:e.target.value}})} placeholder="What is it? Why does it happen? What should I assess or prioritize? Which points do I need to clarify?"/><small>Your response saves with your study data. Compare it with the notes; it is not automatically graded.</small></div><button className="btn primary" onClick={()=>patch({completed:completed.includes(section.key)?completed.filter(k=>k!==section.key):[...completed,section.key],last:section.key})}><Check size={17}/>{completed.includes(section.key)?'Reviewed · undo':'Mark section reviewed'}</button><div className="review-pagination"><button className="btn secondary" disabled={active===0} onClick={()=>jump(active-1)}><ChevronLeft size={16}/>Previous</button><span>{active+1} / {sections.length}</span><button className="btn secondary" disabled={active===sections.length-1} onClick={()=>jump(active+1)}>Next<ChevronRight size={16}/></button></div></TabsContent>
 <TabsContent value="full"><h2>Full detailed notes</h2><p className="small">All working text, in its original order. Nothing is shortened.</p>{find&&<p role="status">{n.text.toLowerCase().split(find.toLowerCase()).length-1} matches</p>}<div className="review-note-text">{marked(n.text)}</div></TabsContent>
 <TabsContent value="summary"><h2>My quick review summary</h2><p className="small">Write your own concise takeaways here. Your full notes stay unchanged.</p><textarea aria-label="My review summary" rows={16} value={n.summary} onChange={e=>update(d=>({...d,notes:d.notes.map(x=>x.id===n.id?{...x,summary:e.target.value}:x)}))} placeholder="Key concepts, assessment findings, nursing priorities, and points to revisit…"/><div className="print-only prewrap">{n.summary}</div></TabsContent></div></Tabs>
 {!!data.highlights[n.id]?.length&&<details className="review-highlights"><summary>My saved passages ({data.highlights[n.id].length})</summary>{data.highlights[n.id].map((h,i)=><blockquote key={i}>{h}</blockquote>)}</details>}</section></div>}
 </>;
}
