'use client';
import {useState} from 'react';
import {ArrowRight,BookOpen,ClipboardList,Search,Target,FileText,CheckCircle2,GraduationCap,RotateCcw} from 'lucide-react';
import {Study} from '@/lib/study';
import {subjects,topics,questions} from '@/lib/content';
import {Progress} from '@/components/ui/progress';
export function ReviewHub({data}:{data:Study}){
 const [search,setSearch]=useState(''),[subject,setSubject]=useState('all'),[onlyNeeds,setOnlyNeeds]=useState(false);
 const latest=new Map<string,boolean>();data.attempts.forEach(a=>a.answers.forEach(x=>latest.set(x.question,x.correct)));
 const rows=topics.map(t=>{const qs=questions.filter(q=>q.topic===t.id);const answered=qs.filter(q=>latest.has(q.id));const correct=answered.filter(q=>latest.get(q.id));const missed=answered.length-correct.length;return {t,qs,answered:answered.length,correct:correct.length,missed};});
 const needs=rows.filter(r=>r.missed>0);const visible=rows.filter(({t,missed})=>(subject==='all'||t.subject===+subject)&&(!onlyNeeds||missed>0)&&[t.title,t.unit,subjects[t.subject]].join(' ').toLowerCase().includes(search.toLowerCase()));
 const next=needs[0]?.t||topics.find(t=>!data.done[t.id])||topics[0];
 return <><div className="page-heading"><div><div className="eyebrow">LEARN · PRACTICE · REVISIT</div><h1>Your review hub</h1><p>Choose a topic, study the notes, then put your understanding to work.</p></div><a className="btn primary" href="#practice"><ClipboardList size={18}/>Build a practice session</a></div>
 <div className="hub-paths"><a href="#library"><span className="hub-step">01</span><BookOpen size={23}/><h2>Understand a topic</h2><p>Quick takeaways, detailed notes, and linked sources.</p><span className="text-button">Explore study guides <ArrowRight size={16}/></span></a><a href="#practice"><span className="hub-step">02</span><GraduationCap size={23}/><h2>Put it into practice</h2><p>Learn with feedback or test yourself before seeing answers.</p><span className="text-button">Open question bank <ArrowRight size={16}/></span></a><a href="#review"><span className="hub-step">03</span><FileText size={23}/><h2>Make it your own</h2><p>Read your lecture notes and explain each section from memory.</p><span className="text-button">Review my notes <ArrowRight size={16}/></span></a></div>
 <div className="hub-focus"><div><span className="pill light"><Target size={14}/>{needs.length?'A TOPIC TO REVISIT':'YOUR NEXT STUDY STEP'}</span><h2>{next.title}</h2><p>{needs.length?'Your latest practice answer needs another look. Read the explanation, then try again.':data.attempts.length?'Continue with a topic you have not marked reviewed.':'Start with a study guide, then take a short practice session to find your gaps.'}</p><div className="button-row"><a href={'#topic/'+next.id} className="btn white">Read the notes <ArrowRight size={16}/></a><a href={'#practice/'+next.id} className="hub-light-link">Practice this topic</a></div></div><div className="hub-focus-stats"><div><strong>{latest.size}<span> / {questions.length}</span></strong><small>unique questions attempted</small></div><div><strong>{needs.length}</strong><small>topics to revisit</small></div><a href="#mistakes">Review my mistakes <RotateCcw size={15}/></a></div></div>
 <section className="card hub-catalog"><div className="section-title"><div><h2>Study by subject & topic</h2><p>Progress reflects your activity in this starter collection.</p></div><span className="pill">{topics.length} study guides</span></div><div className="hub-filters"><label className="review-search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a topic or body system…" aria-label="Find review topics"/></label><select aria-label="Review hub subject" value={subject} onChange={e=>setSubject(e.target.value)}><option value="all">All subjects</option>{subjects.map((s,i)=><option key={s} value={i}>{s}</option>)}</select><button className={'btn '+(onlyNeeds?'active':'secondary')} aria-pressed={onlyNeeds} onClick={()=>setOnlyNeeds(!onlyNeeds)}>Needs review ({needs.length})</button></div>
 {visible.length?subjects.map((s,i)=>{const group=visible.filter(r=>r.t.subject===i);if(!group.length)return null;return <section className="hub-subject" key={s}><h3>{s}</h3>{group.map(({t,qs,answered,correct,missed})=><div className="hub-topic" key={t.id}><div className="hub-topic-name"><small>{t.unit}</small><a href={'#topic/'+t.id}>{t.title}</a><span>{t.minutes} min read · {qs.length} original {qs.length===1?'question':'questions'}{data.done[t.id]&&<span className="hub-reviewed"><CheckCircle2 size={14}/>Notes reviewed</span>}</span></div><div className="hub-topic-progress"><span>{answered?`${correct} / ${answered} latest answers correct`:'Not practiced yet'}</span><Progress value={answered?correct/answered*100:0}/><small>{missed?'Revisit the rationale':answered?'Keep building understanding':'No score yet'}</small></div><div className="hub-topic-actions"><a className="btn secondary" href={'#topic/'+t.id}>Study</a><a className="btn primary" href={'#practice/'+t.id}>Practice</a></div></div>)}</section>}):<div className="empty"><Search size={25}/><h3>No topics match these filters</h3><p>Try another subject or clear your search.</p><button className="btn secondary" onClick={()=>{setSearch('');setSubject('all');setOnlyNeeds(false)}}>Reset filters</button></div>}
 </section><div className="notice"><BookOpen size={20}/><p>One question per starter topic is a small sample, not a mastery or PNLE-readiness measure. Practice sessions can include other topics to reach your chosen length. See the <a className="text-button" href="#library">content inventory</a> for gaps.</p></div>
 </>;
}
