'use client';
import {useEffect,useState} from 'react';
import {toast} from 'sonner';
export function SpaceAccess({code,dirty,loaded,settings}:{code:string;dirty:boolean;loaded:boolean;settings:boolean}){
 const [restore,setRestore]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[show,setShow]=useState(false),[saved,setSaved]=useState(false);
 useEffect(()=>{if(code)setSaved(localStorage.getItem('nr-code-saved-'+code.slice(-12))==='yes');},[code]);
 async function open(e:React.FormEvent){e.preventDefault();if(dirty){setError('Wait for “All changes saved” before opening another study space. Export your data first if saving failed.');return;}setBusy(true);setError('');try{const r=await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:restore})});const body=await r.json() as {error?:string};if(!r.ok)throw Error(body.error||'Could not open study space.');location.reload();}catch(e){setError((e as Error).message);setBusy(false);}}
 function download(){const url=URL.createObjectURL(new Blob([`NurseReady private recovery code\n\n${code}\n\nWebsite: ${location.origin}\nOpen Settings & study data > Open existing study space, then paste this code.\nKeep this file private. Anyone with this code can read, edit, or delete your notes.\n`],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='NurseReady-private-recovery-code.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 if(!settings&&loaded)return <div className="notice"><div><strong>{saved?'Your study space is saved online.':'Keep your recovery code before adding important notes.'}</strong><p>{saved?'Use your code on another device to reopen the same notes.':'No sign-up needed. Your code restores access if you change devices or clear cookies.'} <a className="text-button" href="#settings">{saved?'Study space & recovery':'Save my recovery code'}</a></p></div></div>;

 return <section className="card" style={{marginBottom:'1.5rem'}}><h2>Your private study space</h2><p>No sign-up. Notes and original files are saved online. This browser remembers your space with a cookie. To use the same notes elsewhere, save your recovery code and enter it on the other device.</p>{code&&<><label htmlFor="space-code">Private recovery code</label><input id="space-code" type={show?'text':'password'} readOnly value={code} style={{fontFamily:'monospace',width:'100%'}}/><div className="button-row"><button className="btn secondary" onClick={()=>setShow(!show)}>{show?'Hide code':'Show code'}</button><button className="btn secondary" onClick={async()=>{try{await navigator.clipboard.writeText(code);toast.success('Recovery code copied. Keep it private.');}catch{setShow(true);toast.error('Copy unavailable. Select and copy the code manually.');}}}>Copy code</button><button className="btn primary" onClick={download}>Download recovery code</button><button className="btn secondary" onClick={()=>{localStorage.setItem('nr-code-saved-'+code.slice(-12),'yes');setSaved(true);toast.success('Reminder dismissed. Keep your saved code safe.');}}>{saved?'Code saved':'I saved my code'}</button></div><p className="small">Anyone with this code can read, edit, or delete your notes. If you lose it and clear this browser’s cookies, we cannot recover access. Download study-data exports and original files as extra backups.</p></>}
 <hr/><form onSubmit={open}><h3>Open existing study space</h3><p>On another device, paste your saved recovery code here. This switches spaces; it does not merge or delete the current space.</p><label htmlFor="restore-space">Recovery code</label><input id="restore-space" type="password" autoComplete="off" spellCheck={false} value={restore} onChange={e=>setRestore(e.target.value)} placeholder="Paste your complete recovery code" required disabled={busy} style={{width:'100%'}}/><button className="btn primary" type="submit" disabled={busy||dirty||!restore.trim()}>{busy?'Opening saved space…':'Open my saved notes'}</button>{dirty&&<p>Wait for your changes to finish saving before switching.</p>}{error&&<p className="error-text" role="alert">{error}</p>}</form></section>;
}
